config/routes.rb
Assignment::Application.routes.draw do
  root :to => 'tweets#index'
  get '/get_tweets', to: 'tweets#get_tweets'

end

app/models/tweet.rb
require 'geocoder'
class Tweet
  include Mongoid::Document
  include Mongoid::Geospatial
  include Geocoder::Model::Mongoid

  def self.save_tweet(tweet)
    twt = new(message: tweet.text)
    twt.hashtags = tweet.hashtags.map{|x| x[:text].downcase}
    twt.address = tweet.user.location
    twt.tweeted_at = tweet.created_at
    twt.save!
  end

  field :message, type: String
  field :hashtags, type: Array
  field :coordinates, :type => Point, sphere: true
  field :address
  field :tweeted_at, type: DateTime

  geocoded_by :address               # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  index({ coordinates: '2dsphere', hashtags: 1 }, { background: true })
  # rake db:mongoid:create_indexes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order_by(:tweeted_at.desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  def get_tweets
    lat = params[:latitude].to_i
    lng = params[:longitude].to_i
    r = params[:radius].to_i.fdiv(69)
    @results = Tweet.where(:coordinates => {"$near" => [lat,lng] , '$maxDistance' => r})
    if params[:hashtags].present?
      hashtags = params[:hashtags].downcase.split(' ')
      @results = @results.where(:hashtags => {"$in" => hashtags})
    end
    @results.order_by(:tweeted_at.desc).page(params[:page]).per(10)
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def tweet_params
      params.require(:tweet).permit(:location, :message, :tweeted_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :tweeted_at %><br />
    <%= f.text_field :tweeted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/get_tweets.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="ui-303">
  <div class="o-timeline">
    <% @results.each do |tweet| %>
      <div class="timeline-item">
        <div class="timeline-content">
          <p><%= tweet.message %></p>
          <% unless tweet.hashtags.empty? %>
            <small>
              <% tweet.hashtags.each do |hashtag| %>
                <i>#<%= hashtag %></i>
              <% end %>
            </small>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>
    <% end %>
  </div>
</div>
<hr>

<div class="ui-15">
    <div class="ui-content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12 ui-padd">
            <div class="ui-form">
              <%= form_tag(get_tweets_path(:tab => "drive"), {:method => :get, :class => "form-inline"}) do %>
              <%= hidden_field_tag :latitude , params[:latitude] %>
              <%= hidden_field_tag :longitude , params[:longitude] %>
              <%= hidden_field_tag :radius ,  params[:radius] %>
              <%= text_field_tag :hashtags, params[:hashtags], placeholder: 'Enter hashtags', class: 'form-control' %>
              <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
</div>

app/views/tweets/index.html.erb
<div class="col-md-6 col-md-offset-3">
<% if @tweets.present? %>
  <div class="ui-303">
    <div class="o-timeline">
      <% @tweets.each do |tweet| %>
        <div class="timeline-item">
          <div class="timeline-content">
            <p><%= tweet.message %></p>
            <% unless tweet.hashtags.empty? %>
              <small>
                <% tweet.hashtags.each do |hashtag| %>
                  <i>#<%= hashtag %></i>
                <% end %>
              </small>
            <% end %>
          </div>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>


<div class="ui-15">
    <div class="ui-content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12 ui-padd">
            <div class="ui-form">

                <%= form_tag get_tweets_path, :method => 'get', class: 'form-inline' do %>
                <div class="form-group">
                  <%= text_field_tag :latitude, params[:latitude], placeholder: 'Enter Latitude', class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= text_field_tag :longitude, params[:longitude], placeholder: 'Enter Longitude', class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= text_field_tag :radius, params[:radius], placeholder: 'Enter Radius', class: 'form-control' %>
                </div>
                <%= submit_tag "Search", class: "btn btn-red" %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>
<%= paginate @tweets %>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/page.html.erb
Hello World

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Location:</b>
  <%= @tweet.location %>
</p>

<p>
  <b>Tweeted at:</b>
  <%= @tweet.tweeted_at %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>